#!/usr/bin/env python3

seq_DNA = 'GATGGGATTggggttttccccTCCCATGTGCTCAAGACTGGCGCTaaaaGttttGAGCTTCTCaaaaGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCggggACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGccccCTCTGAGTCAGGAAACAttttCAGACCTATGGAAACTACTTCCTGaaaaCAACGTTCTGTccccCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTccccGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTccccCCGTGGccccTGCACCAGCAGCTCCTACACCGGCGGccccTGCACCAGccccCTCCTGGccccTGTCATCTTCTGTCCCTTCCCAGaaaaCCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTccccTGCCCTCAACAAGATGttttGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACAccccCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGccccCACCATGAGCGCT'

seq_RNA = seq_DNA.upper().replace('T', 'U')

print("a sequencia trocando o T por U fica assim {}".format(seq_RNA))


#seq_DNA_comp =  seq_DNA.upper().replace('A', 'M')
#seq_DNA_comp = seq_DNA_comp.replace('T', 'N')
#seq_DNA_comp = seq_DNA_comp.replace('G', 'O')
#seq_DNA_comp = seq_DNA_comp.replace('C', 'P') 

#seq_DNA_comp = seq_DNA_comp.replace('M', 'T')
#seq_DNA_comp = seq_DNA_comp.replace('N', 'A')
#seq_DNA_comp = seq_DNA_comp.replace('O', 'C')
# seq_DNA_comp = seq_DNA_comp.replace('P', 'G') 

# print("a sequencia de dna complementar é {}".format(seq_DNA_comp)) 





